version: "3"
services:
  app:
    build:
      context: ./Docker-app
    ports:
      - "8081:8080"
    depends_on:
      - db

  db:
    build:
      context: ./Docker-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: devopspassword

